export const DEFAULT_SYMBOLS = ["VNM", "VIC", "HPG", "TCB", "VCB", "FPT", "MWG", "MSN"] as const;

export const POPULAR_SYMBOLS = [
  "VNM",
  "VIC",
  "VHM",
  "HPG",
  "TCB",
  "VCB",
  "CTG",
  "BID",
  "MBB",
  "MSN",
  "MWG",
  "FPT",
  "VRE",
  "GAS",
  "PLX",
  "SAB",
  "VPB",
  "SSI",
  "PNJ",
  "REE",
] as const;

export const HOSE_SYMBOLS = [
  "VNM",
  "VIC",
  "VHM",
  "HPG",
  "TCB",
  "VCB",
  "CTG",
  "BID",
  "MBB",
  "MSN",
  "MWG",
  "FPT",
  "VRE",
  "GAS",
  "PLX",
  "SAB",
  "VPB",
  "HDB",
  "SSI",
  "PNJ",
  "REE",
  "DGC",
  "DHG",
] as const;

export const HNX_SYMBOLS = ["SHB", "EIB", "ACB", "STB", "VND", "HAG", "DBC"] as const;

export const COMPANY_NAMES: Readonly<Record<string, string>> = {
  VNM: "Vinamilk",
  VIC: "Vingroup",
  VHM: "Vinhomes",
  HPG: "Hoà Phát Group",
  TCB: "Techcombank",
  VCB: "Vietcombank",
  CTG: "VietinBank",
  BID: "BIDV",
  MBB: "MB Bank",
  ACB: "ACB Bank",
  STB: "Sacombank",
  MSN: "Masan Group",
  MWG: "Thế Giới Di Động",
  FPT: "FPT Corporation",
  VRE: "Vincom Retail",
  GAS: "PVGas",
  PLX: "Petrolimex",
  SAB: "Sabeco",
  VPB: "VPBank",
  HDB: "HDBank",
  SSI: "SSI Securities",
  VND: "VNDIRECT",
  SHB: "SHBank",
  EIB: "Eximbank",
  PNJ: "PNJ Jewelry",
  REE: "REE Corporation",
  DHG: "Hậu Giang Pharma",
  DGC: "Đức Giang Chemical",
  DBC: "Dabaco",
  HAG: "HAGL",
};
